language: node_js
deploy:
  provider: npm
  email: jesse.luoto@gmail.com
  api_key:
    secure: CDdAJTqdfVyipuNffrBpPE8126zjG54Y/pVryVSB82FijU7CXj8AdR6JWGae10qeGE/6Jgy79JlnO0/mBHsHrkSY05p4w96UetXNw/bzffXdKOfS0OeraBvCl4YCxPgWkKxsLzb9s99DPIisuAPguFC9OsNhQUnegHM6ZKms2kFSasl54NjrW2MaAogESjfYZ5WtISkRaJMnb0Xo/MOuf+FeTspGMeQtVEUZaqtw06YcolUnierl+2Ia3VP3Tb9SJOuKKSXBcXlUEWasshB37OtOE2pbXoaJNHTCv7BbTt5LAQmAyD0F7+y/RON2lOAd8hCIwVsw9ZXP1v5/9pT4ar1M5/O77Zu9jBoxqtkUIBcce012pIHyz7Jswlme5ZGhDURl2lzZJNaXl8W9HToK7Ed6tmMns4yZBj7zMZOqckNiGDrnWznTwVmeh6mo6Oayu9l+QBjxsSQSNB51YNq+3fH2jV8jD/RZgWGydM7f6rW8TPjE1PFiVc7lmcZs4pk1uNTVPhNv79+b42dTJH90C0P5jVzsw39812j0RRzczvKDLErZU5vFeAeP7E1IHXjnRJBNqexQEyQ/taB4bFsWN9mEr6Dq42y2GJFCNhBpXNK7Ld3A1Yu5Km5dST40IIJ4bGjoPeDUaFwktHEJgqWiJDRoFep37zB8flxxUFLVp5A=
  on:
    tags: true
    repo: jehna/ga-lite
env:
- CXX=g++-4.8
before_script:
- yarn lint && yarn build
after_success:
- npm run cover
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - "$HOME/.cache/Cypress"
